name: Build Electron App for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build App
        run: pnpm run build:win

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Github Release
        id:   create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: Release v${{ steps.package-version.outputs.current-version }}
          body: Assets for the latest Windows build.
          draft: false
          prerelease: false

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/QuickCart.exe
          asset_name: QuickCart.exe
          asset_content_type: application/vnd.microsoft.portable-executable
